services:
  app:
    build: .
    container_name: risk_management
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/db_connections_test/risk_management/laravel_connection.txt:/var/www/.env:ro
    ports:
      - "127.0.0.1:9002:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c " mkdir -p /var/www/vendor/mpdf/mpdf/tmp && chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache /var/www/vendor/mpdf/mpdf/tmp && chmod -R 775 /var/www/storage /var/www/bootstrap/cache /var/www/vendor/mpdf/mpdf/tmp && php-fpm"
